name: Deploy CI

on:
  push:
    tags:
      - '*'

env:
  GITHUB_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: node setup
      uses: actions/setup-node@v3
      with:
        node-version: 19
        registry-url: https://npm.pkg.github.com/
        cache: 'yarn'

    - name: install yarn
      run: npm install --global yarn

    - name: install dependencies
      run: yarn install

    - name: Build
      run: make build

    - name: Run deploy
      run: make deploy
